### ISSUE TITLE
SetTimeout Method Doesn't Work When Laptop Asleep

### ISSUE THREAD

**Issue by sdford** [chrisguttandin/worker-timers#168]
I would like to execute a method after a given timeout period (even if the user's laptop is asleep), but that does not happen with the `workerTimers.setTimeout` method. However, `workerTimers.setInterval` does in fact execute even when the user's laptop is asleep.

Is this inconsistency between the two methods' functionality intentional? or am I missing something?

The callback passed to the `workerTimers.setTimeout` method is not executed until the laptop is woken up and the tab is brought into focus. Only then does the countdown for the timeout period seem to resume. Then once the remaining time in the timeout period is finished, the callback is executed.

Here is how setTimeout is called:
```
let timeoutId = workerTimers.setTimeout(() => {
       dispatch(methodToCall)
}, 180000)
```

The `workerTimers.setInterval` function does not have this problem. The interval continues to execute even while the laptop is asleep, which is our desired functionality for the `setTimeout` method as well.

Here is how setInterval is called:
```
let intervalId = workerTimers.setInterval(() => {
     console.log(`Time is: ${new Date().getTime()}`);
 }, 2000)
```

Environment details:
* Google Chrome: 65.0
* Node: v8.6.0
* "react": "15.6.2",
* "worker-timers": "4.0.30"

**Comment by chrisguttandin** [comment]
Hi @sdford,

the implementation of `setInterval()/setTimeout()` is very similar. It is handled by the worker-timers-worker package in case you want to review it yourself: https://github.com/chrisguttandin/worker-timers-worker/blob/master/src/helpers/timer.ts. `setInterval()` and `setTimeout()` both use the native  `setTimeout()` function internally.

I don't know what really happens when a laptop is pretending to sleep. But I would be surprised if it could be woken up by some JavaScript code. If the numbers in your example code are the actual values you used to test the functionality, it could be the case that `setInterval()` keeps working because the laptop never ever falls asleep when it has to do something every 2 seconds. But if you schedule a timeout to fire in 3 minutes it might fall asleep before the timeout is about to fire.

That's of course just a rough guess. Can you please try to run both functions with the same delay?

**Comment by sdford** [comment]
Thanks for the quick response. I believe you're right; at least the explanation sounds believable.

I have increased the timeout to 300000 milliseconds (5 mins), and now observe the same behavior (where `setInterval()` also does not trigger while the laptop is "asleep", similar to `setTimeout`).

It seems the `setInterval` is required with a small enough time period in order to accomplish what I would like.

**Comment by chrisguttandin** [comment]
Hi @sdford,

I'm sorry that worker-timers is not working (or at least is not working as expected) for your use case. I haven't tested that, but I could imagine a push notification may be the only thing which is capable of waking up a laptop. That's just a guess and there is a good chance that it might not work as well. But if it does you could "catch" the notification with a ServiceWorker and handle it as you like without showing anything to the user.

I'm closing this issue now as worker-timers can't be modified to support this use case.
