### ISSUE TITLE
Jest error: TypeError: URL.createObjectURL is not a function

### ISSUE THREAD

**Issue by simondib** [chrisguttandin/worker-timers#317]
Getting this error on Jest execution of unit tests: `TypeError: URL.createObjectURL is not a function`

Have tried adding both `window.URL.createObjectURL = function() {};` to the Jest setup as well as mocking `global.URL.createObjectURL = jest.fn();` prior to test execution with no luck. 

Anyone have any suggestions?

**Comment by chrisguttandin** [comment]
Hi @simondib, I think the error you get is caused by Jest running tests outside the browser. In that case worker-timers will not work. The chapter in the README about [server side rendering](https://github.com/chrisguttandin/worker-timers#server-side-rendering) explains this a little further.

Alternatively you could just run your tests in a real browser with something like [Karma](https://karma-runner.github.io).

**Comment by simondib** [comment]
Thanks @chrisguttandin. I did actually get this working by adding into jest setup file:

```
global.URL.createObjectURL = function() {};
global.URL.revokeObjectURL = function() {};
```

.. as well as importing jsom-worker-fix into my test files.

**Comment by badahov** [comment]
As an option...

`
jest.mock('worker-timers', () => ({
  clearInterval,
  setInterval: (func, delay) => setInterval(func, delay),
}));
`

**Comment by BR0kEN-** [comment]
What I did (webpack):
- Add `__TEST__: JSON.stringify(process.env.NODE_ENV === 'test')` using https://webpack.js.org/plugins/define-plugin/.
- Create a module that encapsulates the work with `setTimeout`, e.g:
  ```typescript
  import { setTimeout as setTimeoutWorker } from 'worker-timers';

  /**
   * @see https://github.com/chrisguttandin/worker-timers/issues/317
   * @see https://github.com/chrisguttandin/worker-timers#server-side-rendering
   */
  const setTimeout = __TEST__
    ? window.setTimeout
    : setTimeoutWorker;
  ```
