### ISSUE TITLE
Edge not working

### ISSUE THREAD

**Issue by simondib** [chrisguttandin/worker-timers#320]
Can't seem to get `workerTimers.setInterval()` working under the latest Edge. No apparent browser console errors. The function doesn't even fire once. I've just imported the module as per the README, nothing fancy.

Downgrading to release 4.0.25 works as expected. Upgrading to 4.0.53 (release before v5) re-introduces the issue.

Using a Webpack build with Babel transpiling to < 2 latest browser releases. 

Is this a known issue?

**Comment by chrisguttandin** [comment]
Hi Simon, thanks for reporting this. It should be fixed now with v5.0.25.

I wasn't aware of the issue because there haven't been any tests running in Edge so far. I added Edge now to the range of tested browsers.

The regression that you found in v4.0.26 was actually an error of mine. I broke the build process unintentionally for IE and probably also for Edge. https://github.com/chrisguttandin/worker-timers/issues/164

But I think the issue you experienced in Edge is a different one. Edge doesn't seem to like immediately revoked object URLs. Therefore I added a little delay before revoking it.

The tests do now run happily in Edge but please let me know if the problem still persists.
