### ISSUE TITLE
worker-timer is failing in  IE11

### ISSUE THREAD

**Issue by jeetAdhikary** [chrisguttandin/worker-timers#411]
Hi  Christoph  , 

I have tried  to use worker-timer in IE11 but it is failing. So I have checked few  arrow Functions are  available which breaks in IE11 . 

Does worker-timer works  in IE11 .. ?  is there any way to use it .. ? 

I have seen the old issue #164  but could not figure it out how to use it .

**Comment by chrisguttandin** [comment]
Hi Jeet,

IE11 is not supported anymore. The browser support is defined here: https://github.com/chrisguttandin/worker-timers/blob/master/config/grunt/webpack.js#L26-L35.

However this package is only a pre bundled combination of [worker-timers-worker](https://github.com/chrisguttandin/worker-timers-worker) and [worker-timers-broker](https://github.com/chrisguttandin/worker-timers-broker). The source code for the worker is [stringified](https://github.com/chrisguttandin/worker-timers/blob/master/src/worker/worker.ts) at build time which is why I needed to make a tradeoff between browser support and code size. But you can also build a custom version which works in the browser that you need to support.

I'm going to close this issue as there is nothing that needs to be done in this repo. But please feel free to let me know if building a custom version doesn't work you.

**Comment by jeetAdhikary** [comment]
Thanks Christoph  . 

I am able to build  worker-timer-worker for IE11 compatible . and it is working perfectly . :)

**Comment by chrisguttandin** [comment]
Good to know. I'm glad you found a way to make it work for you.
