### ISSUE TITLE
Not working when using esbuild 

### ISSUE THREAD

**Issue by raviteja83** [chrisguttandin/worker-timers#422]
Not working when using [esbuild ](https://github.com/evanw/esbuild)to bundle and this is used as a dependency in another package. No worker gets added. Any suggestions or workaround?

**Comment by chrisguttandin** [comment]
Thanks for filing this issue. Sadly I can't reproduce it. Using esbuild works as expected for me. Could you please provide a minimal test case?

Since you mentioned that no worker gets added, this is expected. `worker-timers` inlines the Web Worker code. If you want to extract that into a separate file you can use [`worker-timers-broker`](https://github.com/chrisguttandin/worker-timers-broker) and [`worker-timers-worker`](https://github.com/chrisguttandin/worker-timers-worker) directly.

**Comment by raviteja83** [comment]
@chrisguttandin is it working with minify enabled in esbuild? I remember it was failing when minify is enabled.

**Comment by S1SYPHOS** [comment]
Cannot reproduce this issue either, using current `esbuild` (v0.15.12) - all working as expected over here :confused:
