### ISSUE TITLE
Only minified source code included in this repo

### ISSUE THREAD

**Issue by leothorp** [chrisguttandin/worker-timers#428]
Unless I'm overlooking something, the source code for the main worker-timers-worker package is only included in this repo in minified/stringified form. Why is this? 

Thank you.

**Comment by chrisguttandin** [comment]
Hi @leothorp, you're right. The source code of the worker is inlined here. It's just because this is the only way that I know of to publish something on npm which contains a worker without requiring any manual configuration by the users of the package.

The idea of the `worker-timers` package is to make using it in other projects a little easier. But you could also use the `worker-timers-broker` and `worker-timers-worker` packages directly as I tried to explain in [this comment](https://github.com/chrisguttandin/worker-timers/issues/419#issuecomment-932951680).

Does this answer your question?

**Comment by leothorp** [comment]
It does, thank you.
