### ISSUE TITLE
Add support for Chrome & FireFox extensions

### ISSUE THREAD

**Issue by Serega007RU** [chrisguttandin/worker-timers#434]
Hello! I want to ask you to add support for extensions that run on Chrome or FireFox for Content Scripts.
Our task is to ensure that setInterval and setTimeout work correctly on this page https://www.google.com/recaptcha/api2/demo
Your project works in Chrome Extension, but the problem is that there are 2 more iframes on this web page. As you understand, each iframe has its own runtime environment, or as Google calls it "[Isolated World](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#isolated_world)". For each isolated world, worker-timers will create its own Service Worker. Also, the extension in [Content Script](https://developer.chrome.com/docs/extensions/mv3/content_scripts/) (this is a script that is injected into this page to interact and work with it) also has its own isolated world. And so it turns out that 6 Service Workers will be created for one page. It seems to me that this is quite a lot and resource-intensive.
But the extension has its own [Service Worker](https://developer.chrome.com/docs/extensions/mv3/service_workers/basics/), I want to suggest that you make it so that worker-timers does not create a Service Worker for each isolated world, but uses an existing one that provides an extension.
We have already tried to do this [here](https://github.com/Wikidepia/hektCaptcha-extension/pull/88) on the basis of [HackTimer](https://github.com/turuslan/HackTimer), but it seemed to me that worker-timer would be the best option.
It definitely requires knowledge of the Chrome Extension API, I don't know how difficult it will be and if it's even possible in Node JS, my knowledge of Node JS is bad.
Thank You

**Comment by chrisguttandin** [comment]
Hi @Serega007RU,

I'm sorry, I don't know much about developing extensions. But if a Service Worker of an extension is similar to a regular  Service Worker it's lifetime is controlled by the browser. It may or may not be terminated after being idle for a while. Using it for something like worker-timers would then be impossible since there is no guarantee that calls to setTimeout() or setInterval() keep the Service Worker alive.

worker-timers works by creating a regular Web Worker which is tied to the lifetime of the JavaScript scope that created it. In case of a normal website that is the main document. I'm not sure though what that is in case of an extension. Is it really necessary for your use case to import worker-timers 6 times? Maybe using it in one place is enough.

As far as I can tell the other library works by using the very same principle. It also creates a Web Worker. I wonder why that ends up creating less Web Wokers in the end for your use case.

**Comment by Serega007RU** [comment]
> But if a Service Worker of an extension is similar to a regular Service Worker it's lifetime is controlled by the browser. It may or may not be terminated after being idle for a while. Using it for something like worker-timers would then be impossible since there is no guarantee that calls to setTimeout() or setInterval() keep the Service Worker alive.

Yes, it really is, the Service Worker will be terminated after some time of inactivity, I forgot about it. Service Worker can live for 30 seconds, but Chrome resets the sleep timer if it receives some event, for example [chrome.runtime.onMessage](https://developer.chrome.com/docs/extensions/reference/runtime/#event-onMessage) (this is almost the same as window.onmessage). This is really a problem if you use setTimeout or setInterval for more than 30 seconds.


> worker-timers works by creating a regular Web Worker

I completely forgot about Web Worker. Yes, it will be better than Service Worker and my suggestion is useless then.



> Is it really necessary for your use case to import worker-timers 6 times? Maybe using it in one place is enough.

how do I make it so that I can use 1 Web Worker in different iframes? As far as I know we will not be able to access a Web Worker created in one iframe from another iframe.



> I wonder why that ends up creating less Web Wokers in the end for your use case.

Because in my version I do not create a Web Worker, but use an existing Service Worker that creates an extension. The only thing I forgot to take into account about the Service Worker lifecycle

**Comment by chrisguttandin** [comment]
As I said I don't know much about the way extensions work. To me it looks like you currently use `background.js` instead of a Web Worker. Is that correct? If `background.js` is loaded like a Service Worker and killed by the browser from time to time this is not going to work very reliably.

This library is intentionally split into a worker (https://github.com/chrisguttandin/worker-timers-worker) and a broker (https://github.com/chrisguttandin/worker-timers-broker). The worker-timers package is just a convenient way to use both without much hassle. But you could also use them separately. I guess you could use this to create only one Web Worker.
