### ISSUE TITLE
安装最新版本，子依赖fast-unique-numbers会安装8.0.10版本，导致node@14不可用

### ISSUE THREAD

**Issue by sliwei** [chrisguttandin/worker-timers#435]
依赖关系：
worker-timers@7.0.63版本依赖的worker-timers-broker@^6.0.83
worker-timers-broker@^6.0.83版本又依赖的fast-unique-numbers@^7.0.2

实际上：
安装worker-timers@7.0.63，worker-timers-broker会安装6.0.97，fast-unique-numbers会安装8.0.10，导致node@14无法安装worker-timers

如果依赖的包升级了大版本，你的包也应该升级一个大版本，不然会引起这个问题

现在我只能安装你worker-timers@5.1.9版本才能解决这个问题

**Comment by chrisguttandin** [comment]
Hi @sliwei,

I had to translate your text. This is the English version produced by Google Translate:

> Install the latest version. The sub-dependency fast-unique-numbers will install version 8.0.10, causing node@14 to be unavailable.
> 
> Dependencies:
> worker-timers@7.0.63 version depends on worker-timers-broker@^6.0.83
> The worker-timers-broker@^6.0.83 version also depends on fast-unique-numbers@^7.0.2
> 
> Actually:
> When installing worker-timers@7.0.63, worker-timers-broker will install 6.0.97, and fast-unique-numbers will install 8.0.10, resulting in node@14 being unable to install worker-timers.
> 
> If the dependent package has been upgraded to a major version, your package should also be upgraded to a major version, otherwise this problem will occur.
> 
> Now I can only solve this problem by installing your worker-timers@5.1.9 version

I think the problem is that your package manager treats `worker-timers` as a package which is meant to run on Node.js. But it is (at least as of now) intended to run in the browser only. That's why `worker-timers` doesn't get a major version bump when one of it's dependencies drops support for a particular Node.js version. Since it is intended to run in the browser only, the Node.js version supported by its dependencies doesn't really matter.
